### ISSUE TITLE
`eslint-config-standard` release candidate is broken.

### ISSUE THREAD

**Issue by IanVS** [IanVS/eslint-config-ianvs#1]
So, in order for this package to work, it's necessary to manually remove/adjust the `indent` rule.  This will be fixed once https://github.com/feross/eslint-config-standard/issues/6 is closed.

**Comment by feross** [comment]
This is fixed. 4.0.0 is released!

**Comment by IanVS** [comment]
:tada: Thanks for letting me know!

**Comment by feross** [comment]
No problemo.
